### ISSUE TITLE
Please add a License

### ISSUE THREAD

**Issue by ff6347** [technologiestiftung/werkstatt#1]
See this [GitHub Help](https://help.github.com/en/articles/adding-a-license-to-a-repository) on how to.

Read [this article](https://blog.codinghorror.com/pick-a-license-any-license/) by Jeff Atwood why.

> Because I did not explicitly indicate a license, I declared an implicit copyright without explaining how others could use my code. Since the code is unlicensed, I could theoretically assert copyright at any time and demand that people stop using my code. Experienced developers won't touch unlicensed code because they have no legal right to use it. That's ironic, considering the whole reason I posted the code in the first place was so other developers could benefit from that code. I could have easily avoided this unfortunate situation if I had done the right thing and included a software license with my code.

**Comment by ff6347** [comment]
Bump! @julizet

**Comment by julizet** [comment]
Done! @fabianmoronzirfas 
added MIT license
